# SPDX-FileCopyrightText: 2025 Tobias BÃ¶hm <code@aibor.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build test Image

on:
  push:
    branches:
      - "main"
    paths:
      - testdata/container
      - .github/workflows/build-test-image.yaml

jobs:
  build-and-push-image:
    name: Build and push test image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: aibor/virtrun-test
    strategy:
      matrix:
        arch:
          - flavor: amd64
            arg: x86_64
          - flavor: arm64
            arg: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.arch.flavor }},priority=50
            type=sha,prefix=${{ matrix.arch.flavor }}-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:testdata/container"
          file: ./Dockerfile
          push: true
          build-args: ARCH=${{ matrix.arch.arg }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
